
site:
  theme: BsDoc
  baseUrl: 'https://copper-leaf.github.io/common'
  about:
    siteName: Eden Commons
    siteDescription: A collection of utility classes and tools used throughout other Orchid and Copper Leaf repositories

theme:
  social:
    github: 'JavaEden/Common'
  primaryColor: '#740001'
  bannerColor: '#740001'
  menu:
    - type: 'link'
      title: 'Home'
      url: '#{$0|baseUrl}/'
    - type: 'wiki'
      title: 'Wiki'
      topLevel: true
    - type: 'sourcedocPages'
      moduleType: 'javadoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'javadoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
  trianglifyOptions:
    x_colors: ['#740001', '#eeba30', '#740001']
  useSidebarSearch: true
  legacySearch: false
  metaComponents:
    - type: 'orchidSearch'

allPages:
  components:
    - type: pageContent
      order: 10

wiki:
  includeIndexInPageTitle: false
  sections:
    - json
    - options

javadoc:
  sourceDirs:
    - '../../../../Common/src/main/java'

changelog:
  adapter:
    type: "file"
    baseDir: "./../../../../"

services:
  publications:
    stages:
      - type: githubReleases
        repo: 'copper-leaf/common'
        username: 'cjbrooks12'
        commitish: 'master'
      - type: githubPages
        repo: 'copper-leaf/common'
        username: 'cjbrooks12'
